-- ============================================
-- RESET: Drop ALL objects (reverse FK order)
-- ============================================

-- Drop materialized view refresh functions (from security_rls.sql)
DROP FUNCTION IF EXISTS refresh_mv_orders_by_status() CASCADE;
DROP FUNCTION IF EXISTS refresh_mv_monthly_revenue() CASCADE;

DROP MATERIALIZED VIEW IF EXISTS "mv_orders_by_status" CASCADE;
DROP MATERIALIZED VIEW IF EXISTS "mv_monthly_revenue" CASCADE;
DROP VIEW IF EXISTS "v_active_menus" CASCADE;
DROP VIEW IF EXISTS "v_low_stock_ingredients" CASCADE;
DROP VIEW IF EXISTS "v_pending_reviews" CASCADE;
DROP FUNCTION IF EXISTS fn_update_timestamp() CASCADE;
DROP FUNCTION IF EXISTS fn_order_status_history() CASCADE;

-- New organization tables (must drop before Company/User)
DROP TABLE IF EXISTS "Event" CASCADE;
DROP TABLE IF EXISTS "CompanyWorkingHours" CASCADE;
DROP TABLE IF EXISTS "CompanyOwner" CASCADE;
DROP TABLE IF EXISTS "Company" CASCADE;

DROP TABLE IF EXISTS "OrderOrderTag" CASCADE;
DROP TABLE IF EXISTS "OrderTag" CASCADE;
DROP TABLE IF EXISTS "KanbanColumn" CASCADE;
DROP TABLE IF EXISTS "TicketMessage" CASCADE;
DROP TABLE IF EXISTS "SupportTicket" CASCADE;
DROP TABLE IF EXISTS "Notification" CASCADE;
DROP TABLE IF EXISTS "Message" CASCADE;
DROP TABLE IF EXISTS "TimeOffRequest" CASCADE;
DROP TABLE IF EXISTS "LoyaltyTransaction" CASCADE;
DROP TABLE IF EXISTS "LoyaltyAccount" CASCADE;
DROP TABLE IF EXISTS "ContactMessage" CASCADE;
DROP TABLE IF EXISTS "ReviewImage" CASCADE;
DROP TABLE IF EXISTS "Publish" CASCADE;
DROP TABLE IF EXISTS "DeliveryAssignment" CASCADE;
DROP TABLE IF EXISTS "OrderStatusHistory" CASCADE;
DROP TABLE IF EXISTS "OrderMenu" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "UserPromotion" CASCADE;
DROP TABLE IF EXISTS "Promotion" CASCADE;
DROP TABLE IF EXISTS "Discount" CASCADE;
DROP TABLE IF EXISTS "MenuIngredient" CASCADE;
DROP TABLE IF EXISTS "DishIngredient" CASCADE;
DROP TABLE IF EXISTS "DishAllergen" CASCADE;
DROP TABLE IF EXISTS "_DishAllergens" CASCADE;
DROP TABLE IF EXISTS "_MenuDishes" CASCADE;
DROP TABLE IF EXISTS "MenuImage" CASCADE;
DROP TABLE IF EXISTS "Ingredient" CASCADE;
DROP TABLE IF EXISTS "Allergen" CASCADE;
DROP TABLE IF EXISTS "Dish" CASCADE;
DROP TABLE IF EXISTS "Menu" CASCADE;
DROP TABLE IF EXISTS "Theme" CASCADE;
DROP TABLE IF EXISTS "Diet" CASCADE;
DROP TABLE IF EXISTS "DataDeletionRequest" CASCADE;
DROP TABLE IF EXISTS "UserConsent" CASCADE;
DROP TABLE IF EXISTS "PasswordResetToken" CASCADE;
DROP TABLE IF EXISTS "UserSession" CASCADE;
DROP TABLE IF EXISTS "UserAddress" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "RolePermission" CASCADE;
DROP TABLE IF EXISTS "Permission" CASCADE;
DROP TABLE IF EXISTS "Role" CASCADE;
DROP TABLE IF EXISTS "WorkingHours" CASCADE;
