INSERT INTO "Dish" ("title","description","photo_url","course_type") VALUES
    ('Foie Gras Maison','Foie gras mi-cuit, chutney de figues','/img/dishes/foie-gras.jpg','entree'),
    ('Velouté de Champignons','Velouté onctueux aux cèpes et truffe','/img/dishes/veloute.jpg','entree'),
    ('Tartare de Saumon','Saumon frais mariné aux agrumes','/img/dishes/tartare-saumon.jpg','entree'),
    ('Filet de Bœuf Wellington','Bœuf en croûte, duxelles de champignons','/img/dishes/wellington.jpg','plat'),
    ('Risotto aux Champignons','Riz arborio, champignons de saison','/img/dishes/risotto.jpg','plat'),
    ('Homard Bleu Rôti','Homard breton, beurre clarifié aux herbes','/img/dishes/homard.jpg','plat'),
    ('Côte de Bœuf Grillée','Maturée 30 jours, sel de Guérande','/img/dishes/cote-boeuf.jpg','plat'),
    ('Œufs Bénédicte','Œufs pochés, sauce hollandaise maison','/img/dishes/eggs-benedict.jpg','plat'),
    ('Paris-Brest','Pâte à choux, crème pralinée noisettes','/img/dishes/paris-brest.jpg','dessert'),
    ('Crème Brûlée à la Vanille','Vanille de Madagascar, caramel craquant','/img/dishes/creme-brulee.jpg','dessert'),
    ('Salade César Revisitée','Poulet grillé, croûtons, parmesan','/img/dishes/salade-cesar.jpg','entree'),
    ('Carpaccio de Bœuf','Bœuf cru finement tranché, roquette','/img/dishes/carpaccio.jpg','entree'),
    ('Magret de Canard','Magret rôti, sauce aux cerises','/img/dishes/magret.jpg','plat'),
    ('Dos de Cabillaud','Cabillaud rôti, beurre blanc','/img/dishes/cabillaud.jpg','plat'),
    ('Ratatouille Provençale','Légumes du soleil mijotés','/img/dishes/ratatouille.jpg','plat'),
    ('Tarte Tatin','Pommes caramélisées, pâte feuilletée','/img/dishes/tarte-tatin.jpg','dessert'),
    ('Fondant au Chocolat','Cœur coulant au chocolat noir 70%','/img/dishes/fondant-choco.jpg','dessert'),
    ('Panna Cotta Framboise','Panna cotta vanille, coulis framboises','/img/dishes/panna-cotta.jpg','dessert'),
    ('Gazpacho Andalou','Soupe froide de tomates, concombre','/img/dishes/gazpacho.jpg','entree'),
    ('Tian de Légumes','Courgettes, tomates, aubergines gratinées','/img/dishes/tian.jpg','plat');
